### PR TITLE
Replace docker version check

### LINKED ISSUE #209: docker pip
not compatible with docker pip package 6.0.0 yet pipfile requests any version.

```
2022-08-19 01:[15](https://github.com/HalleyAssist/mothership-api/runs/7910122219?check_suite_focus=true#step:6:16):32,594 root         ERROR    module 'docker' has no attribute 'version_info'
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/docker_squash/image.py", line 357, in _save_image
    if docker.version_info[0] < 3:
AttributeError: module 'docker' has no attribute 'version_info'
```

Please restrict to <6

### PR DESCRIPTION
**Pull request by enterJazz**
Fixes #209

### CODE REVIEW

**Comment by mkesper** [comment]
This should also be tested against docker version < 6 just to be sure.

**Comment by mfortin** [comment]
It works with previous version

```
$ pip3 list | grep docker
docker                                4.3.1
```
and then, in python
```
>>> import docker
>>> docker.version
'4.3.1'
>>> docker.version_info
(4, 3, 1)
>>> docker.__version__.split('.')
['4', '3', '1']
>>>
```

**Comment by mfortin** [comment]
@goldmann can you please review ?

**Review by justcsdr — CHANGES_REQUESTED** [review]
Something like the attached patch it will be more appropriate.
`--- image.py    2022-10-13 07:02:10.963879351 +0300
+++ image.py    2022-10-12 08:12:26.313070906 +0300
@@ -353,8 +353,14 @@

             try:
                 image = self.docker.get_image(image_id)
+                _docker_ver = 0;

-                if docker.version_info[0] < 3:
+                try:
+                    _docker_ver = int(docker.__version__.split('.')[0]);
+                except Exception as e:
+                    _docker_ver = docker.version_info[0];
+
+                if _docker_ver < 3:
                     # Docker library prior to 3.0.0 returned the requests
                     # object directly which cold be used to read from
                     self.log.debug(`

**Comment by goldmann** [comment]
Hey @enterJazz! Thanks for the PR and sorry for being late to the party! I'm not really sure why GH Actions didn't run for this PR (I don't have the PR in my approval list for running Actions as well). Not sure either why CircleCI kicked in since I switched to Actions about a year ago... Either case -- trying to figure out how to do it so that your commit will be preserved. Hang on.

**Comment by goldmann** [comment]
I've opened PR #216 which let me run proper GH Actions. That PR contains your commit. Thank you!

**Pull request closed without merging**
