### PR TITLE
Fix for issue #139

### PR DESCRIPTION
**Pull request by linuxfreakus**
Changes the requirement from `docker-py` to `docker` as detailed in issue #139

### CODE REVIEW

**Comment by linuxfreakus** [comment]
Hmm... looks like the tests didn't all work.  I only ran 2.7 tests locally, didn't notice there would be any difference.  I'll take a look later

**Comment by goldmann** [comment]
Thanks for the PR! Just one note - I would be looking most probably to support both API versions. The reason is that many users still use/pin to the older one and it would be impossible for them to upgrade to new version of squash tool.

**Comment by linuxfreakus** [comment]
Hmm... odd, I just ran the tests for py35 locally and the passed too.

You are correct about supporting both versions.  If it is possible without major shenanigans, that would be ideal.  I couldn't think of a good way to do it myself without messing with the importer and that doesn't sound like fun.

**Comment by linuxfreakus** [comment]
Looks like I could actually put something in setup.py that looks for an extra install option from pip, and then conditionally initialize the client correctly depending on which version is installed.

**Comment by linuxfreakus** [comment]
Well... maybe not actually... looks as if you can only pass extra options to install, and by that time it already has processed requirements file when it runs egg_info (if you suppress using the binary wheel that may not have the right thing in it).

So short of making it an environment variable or making two different builds one for each API, I don't know what else one can do that wouldn't be too ugly -- as if telling users to set an environment variable while running pip wouldn't be ugly, lol.

I don't have as much pure python experience, I'm more of a generalist so there could be a technique I'm not aware of.

Python is a nice language, but its packaging/module system is not my favorite :P

**Comment by TomasTomecek** [comment]
This is the patch I did for sen to use `docker-py-{1,2}` https://github.com/TomasTomecek/sen/commit/52fd9526fb465040589e5d1e60ca1512fe21b477

**Comment by linuxfreakus** [comment]
Yeah, I was thinking I would be able to do something along those lines where the API is actually used in the code @TomasTomecek but I am stuck at trying to have pip correctly install and be satisfied with either version of the API (probably default to the newer one but let people use `--install-option='...'` in a requirements file if they need the older version).... otherwise it will install `docker-py` when I actually want `docker` and the pyenv will have weird behavior.

**Comment by TomasTomecek** [comment]
@linuxfreakus I just switched to `docker` in `requirements.txt`. Since python packaging doesn't support `docker-py<=1.10.6,docker>2`, I'm not sure actually how to do that -- distributions still can patch the sources and people installing from PyPI can get latest greatest.

**Comment by linuxfreakus** [comment]
Yeah, I don't know if there is a good solution other than having people patch... frustrating.

**Comment by linuxfreakus** [comment]
FYI, it seems the official docker client has also begun requiring `docker` as opposed to `docker-py` now also.  I'm assuming eventually more and more people would rather have the newer one that will get API updates.

**Comment by goldmann** [comment]
I'll make a note to look at squashing related issues tomorrow, including this one. Thanks for heads up!

**Comment by goldmann** [comment]
It was fixed in #143, I'm closing this PR, but thanks for the initial work!

**Pull request closed without merging**
