### PR TITLE
Do not read the whole tar, but stream it

### LINKED ISSUE #29: Do not create squashed tar in-memory, store it on disk
When the build is executed on a host that has small amount of RAM and/or the image we squash is big enough - sometimes the tool can eat whole memory and fail with a `MemoryError`.

### PR DESCRIPTION
**Pull request by goldmann**
Fixes #29.

### CODE REVIEW

**Comment by gcstang** [comment]
Is there a change in the command line in order to stream it?

**Comment by goldmann** [comment]
Correct, this change streams the image to the Docker daemon instead of reading it into memory.

**Comment by gcstang** [comment]
Ok, so nothing new to put on the command line it just performs a stream behind the scenes?

**Comment by goldmann** [comment]
Correct.

**Comment by goldmann** [comment]
> Is there a change in the command line in order to stream it?

I misread your comment here and that probably confused you :) Just to be clear - no change in the command line at all, the change is internal and automatic.

**Comment by gcstang** [comment]
No problem, thank you.

Added a new issue, I found it when running on the branch you created for my last issue but it does the same in Master currently. #80

**Pull request merged**
